@startuml

title __VIEWING's Class Diagram__\n

  namespace viewing {
    class viewing.AusgabeRahmen {
        + AusgabeRahmen()
    }
  }
  

  namespace viewing {
    class viewing.CustomZutatRahmen {
        + CustomZutatRahmen()
    }
  }
  

  namespace viewing {
    class viewing.InfoRahmen {
        ~ info : JLabel
        ~ ok : JButton
        ~ InfoRahmen()
    }
  }
  

  namespace viewing {
    class viewing.LogRahmen {
        ~ close : JButton
        ~ smoothieAuswertung : List
        ~ werteAuswertung : List
        ~ LogRahmen()
    }
  }
  

  namespace viewing {
    class viewing.LoginRahmen {
        + LoginRahmen()
    }
  }
  

  namespace viewing {
    class viewing.Rahmen {
        - f1 : FileWriter
        - file1 : File
        - p1L1 : JLabel
        - p1a2Text : JLabel
        - p3Apfel : JButton
        - p3Banane : JButton
        - p3Birne : JButton
        - p3Erdbeere : JButton
        - p3Karotte : JButton
        - p3Kiwi : JButton
        - p3Kohlrabi : JButton
        - p3Melone : JButton
        - p3Pfirsich : JButton
        - p3Spinat : JButton
        - p3Weintrauben : JButton
        - p3erstelleCustomZutat : JButton
        - p3hinzuCustomZutat : JButton
        - p4Entfernen : JButton
        - p4Exit : JButton
        - p4Mixen : JButton
        - p4logFile : JButton
        + Rahmen()
        - aktualisiereAnzeige()
        - p3ZutatenDisappear()
        - p3Zutatenappear()
    }
  }
  

  namespace viewing {
    class viewing.Uebergabe {
        {static} ~ UebergabeZutat : Zutat
    }
  }
  

  viewing.AusgabeRahmen -up-|> javax.swing.JFrame
  viewing.CustomZutatRahmen -up-|> javax.swing.JFrame
  viewing.CustomZutatRahmen o-- model.zutaten.Zutat : customZutat
  viewing.InfoRahmen -up-|> javax.swing.JFrame
  viewing.LogRahmen -up-|> javax.swing.JFrame
  viewing.LoginRahmen -up-|> javax.swing.JFrame
  viewing.Rahmen -up-|> javax.swing.JFrame
  viewing.Rahmen o-- model.smoothiemixer.Smoothiemixer : smoothiemixer
  viewing.Rahmen o-- model.benutzerprofile.Benutzerprofile : user


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
